 CREATE TABLE "KURLYDEV"."TBL_CATEGORY" 
 (	"TIER" NUMBER, 
	"CATENAME" VARCHAR2(50 BYTE), 
	"CATECODE" VARCHAR2(20 BYTE), 
	"CATEPARENT" VARCHAR2(20 BYTE)
 ) 

Insert into KURLYDEV.TBL_CATEGORY (TIER,CATENAME,CATECODE,CATEPARENT) values (1,'채소','A0000',null);
Insert into KURLYDEV.TBL_CATEGORY (TIER,CATENAME,CATECODE,CATEPARENT) values (1,'과일·견과·쌀','B0000',null);
Insert into KURLYDEV.TBL_CATEGORY (TIER,CATENAME,CATECODE,CATEPARENT) values (1,'수산·해산·건어물','C0000',null);
Insert into KURLYDEV.TBL_CATEGORY (TIER,CATENAME,CATECODE,CATEPARENT) values (1,'정육·계란','D0000',null);
Insert into KURLYDEV.TBL_CATEGORY (TIER,CATENAME,CATECODE,CATEPARENT) values (1,'국·반찬·메인요리','E0000',null);
Insert into KURLYDEV.TBL_CATEGORY (TIER,CATENAME,CATECODE,CATEPARENT) values (1,'샐러드·간편식','F0000',null);
Insert into KURLYDEV.TBL_CATEGORY (TIER,CATENAME,CATECODE,CATEPARENT) values (1,'면·양념·오일','G0000',null);
Insert into KURLYDEV.TBL_CATEGORY (TIER,CATENAME,CATECODE,CATEPARENT) values (1,'생수·음료·우유·커피','H0000',null);
Insert into KURLYDEV.TBL_CATEGORY (TIER,CATENAME,CATECODE,CATEPARENT) values (1,'간식·과자·떡','I0000',null);
Insert into KURLYDEV.TBL_CATEGORY (TIER,CATENAME,CATECODE,CATEPARENT) values (1,'건강식품','J0000',null);
Insert into KURLYDEV.TBL_CATEGORY (TIER,CATENAME,CATECODE,CATEPARENT) values (1,'와인','K0000',null);