--------------------------------------------------------
--  DDL for Table TBL_PRODUCT
--------------------------------------------------------

  CREATE TABLE "KURLYDEV"."TBL_PRODUCT" 
   (	"PCODE" NUMBER, 
	"PNAME" VARCHAR2(100 BYTE), 
	"COMPANY" VARCHAR2(50 BYTE), 
	"PRICE" NUMBER, 
	"STOCK" NUMBER, 
	"CATEGORY" VARCHAR2(50 BYTE), 
	"POSTSCRIPT" VARCHAR2(300 BYTE), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"ORG_FILENAME" VARCHAR2(100 BYTE), 
	"STORED_FILENAME" VARCHAR2(100 BYTE), 
	"PREGDATE" DATE, 
	"DISCOUNT" NUMBER, 
	"THISWEEK" VARCHAR2(20 BYTE)
   ) 

Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (45,'[도리깨침] 열무 들기름볶음','도리깨침',5500,30,'F0000','아삭하고 고소한 별미 반찬','달아난 입맛도 금세 되살아나게 하는 시원한 별미 반찬을 찾는 다면, 열무 들기름 볶음만 한 것도 없을 거예요. 도리깨침의 열무 들기름 볶음은 잘 익은 열무 김치의 시원함은 물론, 오동통하게 살이 오른 멸치의 감칠맛과 할머니의 그리운 손맛이 절로 떠오 르는 고소한 들기름의 향이 가득 스며들어있답니다. 팬에 넉넉 히 두른 들기름에 2시간이나 달달 볶았기에 열무 자체에 칼칼한 간이 제법 잘 배어있고요. 따끈한 밥 위에 올려 한입 아삭 베어 먹다 보면 한 그릇을 뚝딱 비우고도, 열무 비빔밥이나 열무국수 로 만들어 즐기고 싶단 생각이 떠나질 않는답니다.','[도리깨침] 열무 들기름볶음.jpg','열무 들기름볶음.jpg',to_date('22/12/03','RR/MM/DD'),0,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (47,'[올리] 수제 그래놀라 3종','올리',10980,20,'I0000','유기농 귀리로 만든 수제 그래놀라','전 공정 수제 방식으로 정성껏 만들어낸 올리의 그래놀라 3종을 소개합니다. 유기농 귀리와 아몬드, 코코넛 오일, 메이플 시럽 등 고품질의 재료를 아낌없이 사용해 완성한 제품인데요. 오븐에 두 번 구워 재료 고유의 고소한 풍미도 한껏 살려냈답니다. 우유, 요거트 토핑은 물론 입이 심심한 순간 쏙쏙집어먹기 편리하도 록 덩어리 형태로 뭉쳐 만들었어요. 고소한 오리지널부터 상큼 한 베리까지, 3가지를 준비했으니 취향에 맞게 골라보세요.','[올리] 수제 그래놀라 3종.jpg','수제 그래놀라 3종.jpg',to_date('22/12/01','RR/MM/DD'),0,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (48,'[그라놀로지] 선물세트 1호','그라놀로지',35000,30,'I0000','실속있게 꾸려넣은 고소한 간식','달콤한 풍미를 품은 영양 간식 선물세트를 만나보세요. 프리미 엄 수제 그래놀라 전문 브랜드인 그라놀로지가 귀리와 각종 견 과류, 과일을 고루 섞어 만든 간식을 선보입니다. 정제 설탕 대신 비정제 원당, 메이플 시럽 등을 재료로 사용하여 건강한 단맛을 내는 점이 눈길을 끌어요. 그라놀로지스트가 직접 엄선하고 관 리한 귀리를 3번에 걸친 저온 로스팅으로 바삭하게 구워냈기에 식감 또한 각별하답니다. 지퍼백 포장된 3종의 그래놀라를 깔끔 한 종이 상자에 넣어 보내드리니, 지인에게 건네는 센스 있는 선 물로 제격일 거예요.','[그라놀로지] 선물세트 1호.jpg','선물세트 1호.jpg',to_date('22/07/07','RR/MM/DD'),20,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (49,'[라아부엘라니에베스] 스페인 수제 감자칩','라아부엘라니에베스',5300,7,'I0000','손으로 정성껏 만들어낸 바삭한 감자칩','감자, 오일, 소금 단 세 가지 재료로 완성한 장인인증 감자칩을 소개할게요. 라아부엘라니에베스는 값비싼 아그리아 감자, 질 좋은 해바라기 오일 그리고 지중해 천일염으로 감자칩을 만들어 요. 이 외에는 어떤 재료도 더하지 않기에, 감자칩 단 한 조각으 로도 명료한 맛을 경험할 수 있지요. 현재까지도 100% 수제 팬 프라이 방식을 고집하는 라아부엘라니에베스의 감자칩은, 까다 로운 자격요건 및 평가절차를 통해 선정되는 카스티야 이 레온 (Castilla y Leon) 장인인증을 획득하기도 했답니다. 지중해의 태양과 장인의 신념이 깃든 감자칩, 지금 컬리에서 만나보세요','[라아부엘라니에베스] 스페인 수제 감자칩.jpg','스페인 수제 감자칩.jpg',to_date('22/12/30','RR/MM/DD'),0,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (50,'[미주라] 통밀 도너츠','미주라',4200,50,'I0000','부드럽고 폭신폭신한 미주라 통밀 도너츠','건강하고 균형 잡힌 간식을 연구하는 이탈리아 브랜드, 미주라 의 통밀 도너츠를 소개합니다. 고소하고 폭신한 빵이 생각날 때, 부담 없이 즐기기 좋은 제품인데요. 통밀가루와 밀 식이섬유, 저 지방 요거트 등을 사용해 1봉 당 134kcal의 칼로리를 자랑한답 니다. 여기에 2.3g의 식이섬유까지 함유하고 있어 더욱 만족스 러우실 거예요. 바쁜 출근길이나 출출한 순간, 우유 혹은 커피와 함께 든든하게 즐겨보세요.','[미주라] 통밀 도너츠.jpg','통밀 도너츠.jpg',to_date('22/05/16','RR/MM/DD'),0,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (51,'[로지오가닉] 스틱젤리 3종','로지오가닉',5900,45,'I0000','젤리로 챙기는 우리 아이 영양','귀여운 일러스트가 그려진 스틱에 글글한 젤리를 담은 로지 오가닉의 젤리 3종을 소개할게요. 재료의 영양을 담은 것은 물론 아이들의 입맛을 고려해 세심하게 만들었어요. 설탕 대신 무농 약 쌀조청으로 달콤함을 더하고, 다양한 과일과 채소 등을 배합 해 새콤달콤한 맛을 완성했죠. 여기에 각 효능에 걸맞은 재미있 는 이름을 붙여 아이들의 마음을 사로잡았답니다. 간식 대용으 로 간편하고 맛있게 재료의 영양을 섭취해보세요.','[로지오가닉] 스틱젤리 3종.jpg','스틱젤리 3종.jpg',to_date('22/07/01','RR/MM/DD'),0,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (52,'[리터스포트] 컬러풀 버라이어티 6종','리터스포트',3280,16,'I0000','풍성하게 전해지는 초콜릿 풍미','독일을 대표하는 초콜릿인 리터 스포트는 알록달록한 컬러의 파 키지와 심플한 사각형의 모양, 다채로운 맛으로 많은 인기를 얻 고 있어요. 그중 컬러풀 버라이어티는 정사각형 디자인의 밀크 초콜릿 사이사이에 요거트, 비스킷, 콘플레이크 등의 재료로 속 을 꽉 채워 씹는 재미와 풍성한 맛을 누릴 수 있는 초콜릿 라인이 에요. 두툼한 초콜릿을 반 가른 뒤 한입 배어 물면 달콤함에 이어 또 다른 풍미가 깊게 전해져오지요. 버터비스킷부터 크랜베리 헤이즐넛까지, 총 6가지 구성으로 준비했으니 기호에 따라 골라 담아가세요','[리터스포트] 컬러풀 버라이어티 6종.jpg','컬러풀 버라이어티 6종.jpg',to_date('22/12/28','RR/MM/DD'),0,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (22,'손질 아귀 800g (생물)','만복수산',12980,7,'C0000','한결 편한 아귀 요리','아귀는 독특한 생김새와 달리, 야들야들하고 쫀득한 속살에 담 백한 맛이 일품이죠. 지방은 적고 단백질이 풍부해 더욱 기특한 데요. 이 매력적인 생선을 간편하게 요리할 수 있도록 손질 아귀 를 준비했어요. 신선한 국산 아귀의 머리와 내장을 제거하고 요 리하기 좋은 크기로 썰어 담았답니다. 생물 특유의 신선함과 풍 미, 탄력도 모두 갖추고 있지요. 속 시원한 매운탕부터 다양한 채 소를 곁들인 아귀찜까지, 다양한 방법으로 요리해 즐겨보세요.','손질 아귀 800g (생물).jpg','손질 아귀 800g (생물).jpg',to_date('22/06/14','RR/MM/DD'),0,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (24,'서해안 다짐 대구살 80g (냉동)','천일식품',9500,17,'C0000','부드럽고 담백한 국산 대구살','식사 준비를 한결 편하게 만들어줄 서해안 다짐 대구살을 만나 보세요. 차가운 서해 바다에서 어획한 대구의 속살만 발라내어 곱게 다졌어요. 손질 후 곧바로 급속 냉동한 덕분에 담백한 맛과 부드러운 살결이 오롯이 살아있지요. 두 팩으로 조금씩 나눠 담 았기에 필요한 만큼 손쉽게 꺼내 쓸 수 있답니다. 죽이나 스튜, 대구전 등 다양하게 활용해 보세요. 아이를 위한 첫 생선으로도 알맞을 거예요.','서해안 다짐 대구살 80g (냉동).jpg','서해안 다짐 대구살 80g (냉동).jpg',to_date('22/07/19','RR/MM/DD'),30,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (27,'[양포어장] 과메기 야채세트 807g (냉장)','만복수산',39900,13,'C0000','간편하게 즐기는 겨울 별미','겨울이 제철인 과메기는 추운 계절이 기다려지는 이유 중 하나 지요. 컬리는 오랫동안 과메기를 만들어온 양포어장의 과메기 세트를 준비했어요. 양포어장의 과메기와 떼려야 뗄 수 없는 미역, 채소와 함께 넣었으니 그저 맛있게 즐기기만 하면 되죠. 배추 한 장을 집어 들어 김과 미역, 과메기를 올리고, 마늘과 고추를 입맛 따라 얹은 다음 초고추장에 찍어 한입 가득 넣어보세요. 과 메기 특유의 고소한 향과 짭조름하지만 담백한 맛이 입안에 차 오를 거예요.','[양포어장] 과메기 야채세트 807g (냉장).jpg','과메기 야채세트 807g (냉장).jpg',to_date('22/02/16','RR/MM/DD'),0,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (29,'[소호담] 태우1+ 한우 실속 모둠세트 (냉동)','소호담',109000,26,'D0000','다양한 부위를 함께 즐기는','좋은 것으로만 엄선한 컬리의 선물세트 브랜드, 소호담으로 따뜻한 마음을 전해보세요. 태우한우는 우리나라 축산 유통의 거점, 마장동에 위치한 축산전문 기업입니다. 무려 30년이 넘는 시간동안 축적된 태우만의 노하우와, 엄격한 품질관리 아래 수 준 높은 한우를 생산하고 있어요. 실속 모둠세트에는 다양한 조리 목적에 맞춰 부위를 선별, 정형한 한우를 담았어요. 구이용 등 심과, 국거리용 사태, 불고기용 목심으로 구성했습니다. 소고기 의 다채로운 맛을 사랑하는 분께 추천드려요.','[소호담] 태우1+ 한우 실속 모둠세트 (냉동).jpg','태우1+ 한우 실속 모둠세트 (냉동).jpg',to_date('22/12/18','RR/MM/DD'),40,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (31,'[kims butcher] 호주 부채살 돌돌말이 600g (냉동)','kims butcher',17990,22,'D0000','간편하게 즐기는 부채살','알맞게 구운 소고기는 언제 먹어도 참 만족스러운 음식이죠. 부 담 없이 즐길 수 있도록, Kims butcher가 깐깐하게 선택하고 선보이는 소고기를 만나보세요. 부채살은 하얀 마블링 사이로 미세한 힘줄이 뻗어 있어, 육즙이 고소하고 육질이 비교적 탄탄 한 부위인데요. 한층 부드럽게 즐길 수 있도록, 얇게 썰어 담은 호주산 부채살 대패 상품을 가져왔어요. 불판에 올리면 빠르게 익기 시작하니 간편하고 600g씩 넉넉하게 담아 여럿이 즐기기 에도 넉넉해요. 그대로 노릇하게 구워 먹어도 좋고, 육수에 퐁당 담궈 샤브샤브로 즐기기에도 제격이에요.','[kims butcher] 호주 부채살 돌돌말이 600g (냉동).jpg','호주 부채살 돌돌말이 600g (냉동).jpg',null,20,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (32,'[선물세트] 미국산 초이스 LA 꽃갈비 세트(2kg)/소스 증정','갈비세상',179000,1,'D0000','선물하기 좋은 달달한 꽃갈비','마블링이 우수한 초이스 등급 LA 꽃갈비와 소갈비 전용 양념소 스를 한데 담은 든든한 선물세트를 소개할게요. 불필요한 지방 과 근막을 섬세하게 제거해 부드러운 살코기를 맛볼 수 있는 것 은 물론이고요. 손에 쥐고 먹기 편한 크기로 정형해 뼈를 잡고 쏙 쏙 뜯어 먹는 재미도 느낄 수 있답니다. 짭조름한 양념도 함께 보 내드리니 추가 재료 준비 없이 알맞게 구워만 주세요. 고급스러 운 부직포 가방에 담겨 있어, 선물용으로도 제격이랍니다.','[선물세트] 미국산 초이스 LA 꽃갈비 세트(2kg) 소스 증정.jpg','미국산 초이스 LA 꽃갈비 세트(2kg) 소스 증정.jpg',to_date('22/11/22','RR/MM/DD'),15,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (33,'[kims butcher] 미국산 초이스 LA꽃갈비 1kg (냉동)','kims butcher',49900,4,'D0000','LA갈비를 집에서 간편히','알맞게 구운 소고기는 언제 먹어도 참 만족스러운 음식이죠. 부 담 없이 즐길 수 있도록, Kims butcher가 깐깐하게 선택하고 선보이는 미국산 LA 꽃갈비를 만나보세요. 살결이 곱고 지방이 골고루 분포된 초이스 등급의 갈비 부위를 가로 방향으로 정형 했어요. 덕분에 갈비뼈가 나란히 드러나 손으로 잡고 뜯어 먹는 재미가 있답니다. 달콤짭조름한 양념을 입혀 특별한 날에 어울 리는 근사한 메인요리로 마련해 보세요.','[kims butcher] 미국산 초이스 LA꽃갈비 1kg (냉동).jpg','미국산 초이스 LA꽃갈비 1kg (냉동).jpg',null,45,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (34,'[THE짙은] TBD 삼겹살 구이용 300g','THE짙은',12500,55,'D0000','신선함이 살아있는','언제나 우리 일상에 맛있는 순간을 선사하는 돼지고기, 한결 특 별하게 즐기고 싶다면 주목해 주세요. YBD는 탄탄한 육질이 돋 보이는 버크셔와 깊은 감칠맛을 지닌 듀록의 장점을 고루 갖춘 품종인데요. 도드람의 프리미엄 브랜드라는 위상에 걸맞게 전용 농장에서 세심하게 키워냈답니다. 입안 가득 터져 나오는 촉촉 한 육즙을 느낄 수 있도록, 삼겹살을 2.5cm 두께로 정형해 선보 이니 주저 말고 선택해 보세요.','[THE짙은] TBD 삼겹살 구이용 300g.jpg','TBD 삼겹살 구이용 300g.jpg',to_date('22/11/18','RR/MM/DD'),17,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (53,'[메르시] 스톡 초콜릿 3종','메르시',8500,64,'I0000','하나씩 꺼내 즐기는 초콜릿 풍미','메르시는 독일에서 건너온 초콜릿 브랜드예요. 감사합니다라 는 뜻이 담긴 독일어 메르시(Merci)가 브랜드 이름에 그대로 쓰여진 만큼 누군가에게 마음을 전할 선물로도 알맞지요. 메르 시의 초콜릿은 코코아 버터, 코코아 매스 등의 단순한 재료로 초 콜릿 본연의 풍미를 끌어내기로 잘 알려져 있는데요. 그중 스톡 초콜릿은 초콜릿을 낱개로 고급스럽게 포장하여 상자에 담은 제 품이에요. 가장 기본이 되는 밀크초콜릿부터 헤이즐넛, 프랄린 크림 등 초콜릿에 맛의 변주를 조금씩 준 초콜릿까지 다채롭게 구성돼 골라 먹는 재미도 쏠쏠하답니다. 각기 다른 필링으로 채 워진 초콜릿이 전하는 즐거움을 메르시의 스톡 초콜릿으로 누려 보세요.','[메르시] 스톡 초콜릿 3종.jpg','스톡 초콜릿 3종.jpg',to_date('22/11/19','RR/MM/DD'),10,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (1,'무농약 깐쪽파 200g','해달친환경',3090,30,'A0000','쪽 뻗은 향신채소. 무농약 깐쪽파','파와 양파의 장점만을 쏙쏙 모아놓은 듯한 쪽파는 참 기특한 채소에요. 특유의 은은한 향에, 대파보다 매운맛이 적어 두루 쓰임새가 좋은데요. 컬리는 무농약 농법으로 건강하게 기른 쪽파를 준비했습니다. 흙을 떨어낸 후, 뿌리 부분을 손질한 깐쪽파를 알맞은 양으로 담았어요.  김치나 김치의 속재료는 물론, 각종 반찬으로도 활용해 보세요. 살짝 데쳐서 초장에 찍어 드시거나, 해물과 함께 노릇한 파전으로 즐겨도 좋고요. 기름진 고기를 먹을 때 곁들이면 입 안 가득 개운함까지 더할 수 있을 거에요.','무농약 깐쪽파 200g.jpg','무농약 깐쪽파 200g.jpg',to_date('22/11/01','RR/MM/DD'),12,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (2,'베이비 비트 250g','리더브랜드',6400,25,'A0000','작지만 강력함으로 똘똘 뭉친 수퍼푸드 베이비 비트','선명한 자색이 아름다운 뿌리채소 미니 비트를 만나보세요. 크기는 작지만 필수 아미노산, 안토시아닌 등의 영양 성분이 가득한 슈퍼푸드랍니다. 청정 지역인 뉴질랜드산 베이비 비트 뿌리의 껍질을 벗기고 진공포장한 제품으로 요리에 간편하게 활용하시기 좋아요. 포장을 바로 뜯어서 샐러드, 주스로 만들어 드셔도 좋고, 요거트와 함께 푸드 프로세서에 갈아 간편한 아침 식사로도 추천한답니다.','베이비 비트 250g.jpg','베이비 비트 250g.jpg',to_date('22/11/12','RR/MM/DD'),0,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (3,'친환경 깐 생강 50g','아이농',2990,57,'A0000','요리의 풍미를 더하는 간편 향신채','잡내를 없애고 풍미를 더해주는 생강, 울퉁불퉁한 모양 탓에 손질이 어려웠을 텐데요. 이젠 번거로움 없이 간편하게 사용해 보세요. 무농약 생각 1개를 세척한 후, 깔끔하게 껍질을 벗겨냈어요. 무농약으로 재배해 안심이고, 손질 및 뒷처리 걱정이 없으니 원하는 형태로 썰어 쓰면 돼죠. 풍성한 맛을 위한 기본 양념부터, 육류와 환상의 궁합을 자랑하는 채 썬 생강까지 요리의 적재적소에 활용해 보세요','친환경 깐 생강 50g.jpg','친환경 깐 생강 50g.jpg',to_date('22/11/08','RR/MM/DD'),0,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (4,'세발나물 150g','샤인트리',1790,31,'A0000','갯벌의 풍미를 머금은 나물','갯벌에서 자라난다고 해서 갯나물, 혹은 가늘고 낭창한 잎이 새의 발을 닮았다고 해서 세발나물이라고 불리는 이 채소는 참 독특한 맛을 낸답니다. 사근사근한 식감과 옅은 풋내, 은은한 짭조름함이 느껴지는데요. 식이섬유는 물론, 다양한 비타민과 무기질을 함유하고 있답니다. 생으로 요리에 곁들여 먹거나, 식감 좋은 전으로 부쳐내보세요. 된장이나 간장 양념을 더해 무쳐내면 건강한 반찬이 뚝딱 완성이랍니다.','세발나물 150g.jpg','세발나물 150g.jpg',to_date('22/11/13','RR/MM/DD'),10,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (5,'유채나물 150g','샤인트리',2490,20,'A0000','미각을 깨우는 신선한 맛','자극적인 음식 사이에서도 특유의 싱그러움으로 입맛을 돋우는 식재료, 바로 유채나물입니다. 어린 열무 잎을 빼담아 낯설지 않게 즐길 수 있는 나물인데요. 생으로 맛볼 때는 풋풋하면서도 아삭한 식감을 자랑하지만, 살짝 데친 후에는 금세 촉촉하고 야들야들해지죠. 국내 농가에서 재배한 신선한 유채나물을 부담 없는 양으로 담아 전해드릴게요. 갖가지 밥반찬을 만들 때 두루두루 활용하기 좋고요. 삼겹살 등 기름이 많은 육류를 드실 때도 유채로 겉절이를 무쳐 상큼함을 더해보세요.','유채나물 150g.jpg','유채나물 150g.jpg',null,20,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (6,'돌나물 150g','샤인트리',1690,20,'A0000','풋풋하고 쌉싸름한 향기','돌에 살면서 번진다 하여 돌나물 이라 이름 붙은 이 식재료는 지역에 따라 돗나물이나 돈나물로 불리기도 합니다. 작고 통통한 잎 속에 수분이 가득해, 아삭아삭 씹히는 식감이 무척 독특한데요. 개운하면서도 깔끔한 풍미를 자랑하기에 가볍게 무쳐 먹기 좋답니다. 봄에만 짧게 누릴 수 있던 그 맛, 이제 컬리를 통해 간편하게 만나보세요. 국내 농가에서 재배한 신선한 돌나물을 부담 없는 양으로 담아 전해드려요. 물에 살살 씻은 뒤 드레싱을 둘러 식전에 새콤하게 즐겨도 좋고요. 초고추장에 푹 찍어 드시면, 잃어버렸던 입맛도 금세 되찾을 수 있을 거에요.','돌나물 150g.jpg','돌나물 150g.jpg',null,0,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (7,'달래 60g','샤인트리',2690,21,'A0000','봄을 알리는 톡 쏘는 향긋한 봄나물','톡 쏘는 매콤한 향과 쌉싸래한 내음을 품은 달래, 미각을 깨우는 대표 봄나물입니다. 그저 봄이 오기만을 기다릴 수 없는 컬리는 국내 농가에서 재배한 신선한 달래를 문 앞까지 전해드려요. 아담하게 차오른 알뿌리며, 곧게 자라난 잎이며 저마다 파릇파릇한 기운을 머금고 있는데요. 달래 본연의 향미를 제대로 맛보고 싶다면 알뿌리를 살짝 찧어 조리해 보세요. 양념장에 조물조물 무치거나, 장아찌 혹은 김치를 담가도 좋고요. 팔팔 끓어오르는 찌개에 듬뿍 얹어도 무척 근사하답니다. 쫑쫑 선 달래로 달래장을 만들어두면 반찬 없이도 밥 한 그릇은 금세 비울 거에요. 산뜻한 제철 달래를 컬리를 통해 다채롭게 즐겨보세요.','달래 60g.jpg','달래 60g.jpg',null,0,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (8,'김장용 평창 고랭지 절임 배추 10kg','맑은물속',39900,11,'A0000','잘 절여진 김장용 배추','김장에 있어 가장 중요한 것은 바로 실하고 품질 좋은 배추입니다. 배추의 품질로 김치의 맛이 좌우된다고 해도 과언이 아닐 정도죠. 컬리는 김장용 평창 고랭지 절임 배추를 준비했습니다. 고랭지에서 튼실하게 길러낸 배추를 엄선해 천일염으로 18~23시간 정도 절여냈는데요. 이후 수작업으로 3번에 걸쳐 배추를 세척해 담았어요. 김장용 절임 배추로 번거로움 없이 손쉽고 간편하게 김치를 담아보세요.','김장용 평창 고랭지 절임 배추 10kg.jpg','김장용 평창 고랭지 절임 배추 10kg.jpg',null,0,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (9,'김장용 알타리 무 1.5kg','맑은물속',7490,5,'A0000','아삭함이 오래가는 싱싱한 무','김장 한 번 하려면 갖은 수고와 번거로움이 이만저만이 아니죠. 김장을 하는 김에 다양한 종류의 김치를 함께 담는 분도 많으실 텐데요. 컬리는 총각김치에 알맞은 알타리무를 1단씩 보내드려요. 무청까지 붙어있는 싱싱한 상태로 껍질을 제거하지 않고 보내드린답니다. 깨끗하게 세척한 뒤 원하는 크기로 잘라 절여보세요. 아삭하게 입맛 돋우는 총각김치로 제격일 거예요.','김장용 알타리 무 1.5kg.jpg','김장용 알타리 무 1.5kg.jpg',null,0,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (10,'[새벽수확] 친환경 하우스 설향 딸기 500g','친환경하우스',17900,3,'B0000','친환경으로 더 건강한 딸기','살짝만 베어 물어도 입안 가득 상큼함이 번지는 새빨간 과일. 지금부터 봄까지 열심히 먹어야 하는 딸기입니다. 컬리는 국내에서 재배 중인 다양한 딸기 품종들을 차례로 선보입니다. 그중에서도 우리나라를 대표하는 딸기 품종 설향을 소개할게요. 통통하고 야무진 생김새를 지닌 설향은 과즙이 풍부하고, 상쾌하면서도 시원한 단맛을 뽐내는데요. 화학약품이나 농약 사용 없이, 벌통을 설치한 하우스 안에서 수정하고 재배했기에 더욱 깨끗하고 안전하답니다. 입안 가득 퍼지는 딸기의 새콤달콤한 향미를 마음껏 즐겨보세요.','[새벽수확] 친환경 하우스 설향 딸기 500g.jpg','친환경 하우스 설향 딸기 500g.jpg',null,0,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (11,'무농약 제주 레몬 450g (3~5입)','자연마을',7900,15,'B0000','인공 처리를 하지 않아 더 신선한','비타민 C의 왕이라 불리는 레몬은 껍질까지도 사용하는 과일이죠. 컬리의 레몬은 제주 농가에서 무농약으로 재배했기에 더욱 안심할 수 있답니다. 제주 레몬은 완연한 노란색부터 끝부분이 살짝 녹색을 띠기도 하는데요. 이는 인위적인 코팅을 하지 않고 레몬 본연의 맛과 향이 풍부할 때 수확하기 때문이랍니다. 제주의 따사로운 햇살 아래 건강하게 자란 친환경 레몬으로 각종 요리에 상큼한 매력을 더해보세요.','무농약 제주 레몬 450g (3~5입).jpg','무농약 제주 레몬 450g (3~5입).jpg',null,0,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (12,'유기농 햇 정안밤 800g','자연마을',10500,12,'B0000','노랗고 포근한 단맛의 유혹, 공주에서 재배한 정안밤','충남 공주 정안면은 밤 재배 역사가 긴 만큼, 품질 좋은 밤을 생산하기로 유명한 곳이에요. 컬리가 지금 소개하는 정안밤은 사방이 산으로 둘러싸인 분지 지형의 정안면에서 수확해, 알이 굵고 단단하면서 당도도 훌륭하지요. 화학 비료를 사용하지 않고, 오로지 친환경 퇴비로만 밤나무를 키워냈기에 더욱 안심하고 드실 수 있답니다. 정안밤을 따끈따끈하게 찌거나 노릇하게 구워 즐겨보세요. 안에 든 노란 속살을 달큼한 맛을 한 아름 품고 있으니까요. 알알이 여문 가을의 풍미, 컬리를 통해 손쉽게 만나보세요.','유기농 햇 정안밤 800g.jpg','유기농 햇 정안밤 800g.jpg',null,0,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (16,'시나노골드(금사과) 1.3kg (5~7입)','쥬청과',10900,5,'B0000','달콤함과 새콤함의 적절한 조화, 황금빛 시나노 골드','홍옥이나 부사처럼 빨강게 익어가는 사과가 있는가 하면, 노랗 게 여무는 사과도 있어요. 금사과로도 불리는 시나노 골드는 처 음 열매가 맺혔을 땐 연둣빚을 띠고 있지만, 시간이 지날수록 밝은 노란색으로 물들어 가지요. 아삭아삭한 식감과 수분감이 뛰 어나고, 신맛과 단맛의 조화가 무척 훌륭한 사과랍니다. 향기는 또 어떨까요. 사과 본연의 존재감을 그대로 드러내듯, 기분 좋게 번지는 그윽한 향은 모자람이 없답니다.','시나노골드(금사과) 1.3kg (5~7입).jpg','시나노골드(금사과) 1.3kg (5~7입).jpg',null,0,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (17,'[새벽수확] GAP 논산 설향 딸기 500g','쥬청과',15900,3,'B0000','논산에서 수확한 신선함','풍부한 일조량과 비옥한 토양을 지닌 충남 논산은 딸기 특산지 로 전국적인 명성을 떨치고 있는데요. 컬리는 그중에서도 우리 나라를 대표하는 설향 품종을 골라 준비했습니다. 통통하고 야 무진 생김새를 지닌 설향은 과즙이 풍부해, 시원하면서도 상쾌 한 단맛을 뽐내는데요. 특히 지금 선보이는 GAP 논산 딸기는 병 해충 발생을 줄이기 위하여, 수경재배 방식을 사용해 균일하면 서도 높은 품질을 자랑합니다. 맑고 새콤달콤한 과즙이 함뿍 배 어 나오는 제철 딸기로 일상을 기분 좋게 물들여 보세요.','[새벽수확] GAP 논산 설향 딸기 500g.jpg','GAP 논산 설향 딸기 500g.jpg',null,0,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (18,'엔비사과 1.3kg (5입)','쥬청과',14900,15,'B0000','특별한 향긋함 가득','자그만 크기에 조금은 다른 빛깔을 뽐내는 사과, 바로 엔비 (Envy)사과입니다. 국내 농가에서 정성껏 기른 엔비사과를 준비 했어요. 뉴질랜드에서 개량한 신품종 사과로, 특유의 산뜻한 향 과 새콤한 맛이 특징이죠. 살짝 퍼석하게 씹히지만, 신맛 뒤에 서 서히 우러나오는 단맛이 매력적이랍니다. 신선하게 드실 수 있 는 양으로 보내 드리니, 상큼하게 베어 물어 보세요.','엔비사과 1.3kg (5입).jpg','엔비사과 1.3kg (5입).jpg',null,0,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (19,'손질 민물장어 (자포니카) 400g (생물)','만복수산',35900,3,'C0000','고소한 장어 요리를 손쉽게','씹을수록 쫀득한 식감을 자랑하는 국내산 자포니카종 민물장어 를 소개합니다. 고소한 맛에 영양 가득한 장어지만 직접 요리하 자니 크기부터 손질까지 부담스러울 때가 있죠. 몸통부터 꼬리 까지 두툼한 크기의 생물을 어획하여 바로 요리에 활용할 수 있 도록 머리와 뼈를 말끔히 제거했어요. 한 마리씩 개별 포장하여 보내 드리니 부담 없이 꺼내어 사용해 보세요.','손질 민물장어 (자포니카) 400g (생물).jpg','손질 민물장어 (자포니카) 400g (생물).jpg',null,0,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (20,'조림용 고등어 660g (2마리) (생물)','만복수산',9900,22,'C0000','푹 조릴수록 맛있는 생선','오늘은 어떤 반찬을 할까 고민 중이라면, 매콤한 양념이 쏙쏙 배 어든 고등어 조림을 추천할게요. 번거롭게 손질할 필요 없는 조 림용 고등어를 준비했거든요. 국산 고등어의 머리와 내장을 제 거하고 적당한 크기로 썰어 담았어요. 싱싱한 생물 상태로 보내 드리니, 세척만 하면 곧바로 요리할 수 있답니다. 도톰하고 큼직 한 고등어 2마리 분량이라 든든한 밥반찬으로 충분할 거예요.','조림용 고등어 660g (2마리) (생물).jpg','조림용 고등어 660g (2마리) (생물).jpg',null,0,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (21,'구이용 삼치 320g (생물)','만복수산',7800,5,'C0000','간단히 굽기 좋은 생선','오늘은 어떤 반찬을 할까 고민 중이라면, 간단히 구워 먹을 수 있 는 구이용 삼치를 추천할게요. 싱싱한 국산 삼치의 머리와 내장 을 말끔히 제거하고 생물 상태 그대로 포장했답니다. 곧바로 구 워 먹기 좋게 손질했으니 소금을 뿌려 노릇노릇하게 구워 드셔 보세요. 살이 부드럽고, 담백하면서도 고소하니 누구나 맛있게 즐길 수 있을 거예요. 등 푸른 생선답게 DHA, 단백질 등 영양이 풍부해 아이들을 위한 반찬으로도 제격이랍니다.','구이용 삼치 320g (생물).jpg','구이용 삼치 320g (생물).jpg',null,2,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (35,'[THE짙은] YBD 돈마호크 구이용 300g','THE짙은',25100,30,'D0000','쫄깃함과 신선한 선택','언제나 우리 일상에 맛있는 순간을 선사하는 돼지고기, 한결 특 별하게 즐기고 싶다면 주목해 주세요. YBD는 탄탄한 육질이 돋 보이는 버크셔와 깊은 감칠맛을 지닌 듀록의 장점을 고루 갖춘 품종인데요. 도드람의 프리미엄 브랜드라는 위상에 걸맞게 전용 농장에서 세심하게 키워냈답니다. 근사한 홈파티를 계획 중인 분이라면 삼겹, 등심, 갈빗살을 모두 맛볼 수 있는 돈마호크를 추 천할게요. 압도적인 비주얼부터 먹는 재미까지 누릴 수 있으니 식탁을 빛내는 주인공으로 제격일 거예요.','[THE짙은] YBD 돈마호크 구이용 300g.jpg','YBD 돈마호크 구이용 300g.jpg',null,0,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (36,'[하이포크] 한돈 LA갈비 800g(냉동)','하이포크',12900,10,'D0000','한돈으로 즐기는 갈비','명절이나 모임에 등장하는 요리로 달짝지근한 갈비를 빼놓을 수 없죠. 하이포크가 선보이는 한돈 LA갈비로 안심하고 그 맛을 누 려보세요. 신선한 국내산 갈비를 엄선한 뒤 손에 쥐고 먹기 좋은 모양으로 정형해 담았어요. 해동 후 핏물을 제거해 갖은 양념과 함께 재운 뒤, 노릇하게 구워주면 쫄깃한 LA갈비가 금세 완성된 답니다. 넉넉한 800g 용량이라 더욱 마음에 드실 거예요.','[하이포크] 한돈 LA갈비 800g(냉동).jpg','한돈 LA갈비 800g(냉동).jpg',null,5,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (37,'[미자언니네] 새우 시금치나물','미자언니네',5500,9,'F0000','건강한 한끼','선미자 요리연구가의 노하우로 완성한 새우 시금치나물을 소개 할게요. 뜨거운 물에 살짝 데친 뒤 참기름을 넣고 조물조물 무친 시금치나물에 먹음직스러운 새우가 들어갔어요. 연한 시금치를 꼭꼭씹을수록 부드러운 단맛이 입안을 맴돌고, 글탱글한 새 우의 속살이 풍성한 맛을 더한답니다. 우리집 식탁을 풍성하게 채워줄 색다른 밑반찬이 필요하셨다면, 간편하게 챙겨 보세요.','[미자언니네] 새우 시금치나물.jpg','새우 시금치나물.jpg',null,4,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (38,'[소중한식사] 소고기 버섯 전골','소중한식사',20000,11,'F0000','취향대로 끓여서 완성하는','가족끼리 먹을 메인 요리가 마땅치 않은 날, 따뜻하고 든든한 한 그릇 요리가 먹고 싶은 날, 소중한식사의 소고기 버섯 전골을 선 택해보세요. 이 제품은 손질이 끝난 재료를 보내 가정에서 직접 요리를 하실 수 있도록 구성한 밀키트입니다. 전골 고기와 육수, 모둠 야채를 한 봉씩 보내드리니 취향대로 완성해보세요. 소중한식사는 국산 다시마와 북어 머리를 맑게 우린 후 익힌 소고기 와 함께 정갈하게 담아냈습니다. 배추, 각종 버섯, 대파, 청경채 등 갖은 야채도 말끔하게 손질했지요. 조리하실 때에는 냄비에 육수를 붓고 야채를 보기 좋게 담기만 하면 준비가 끝납니다. 소 고기가 이미 다 익었기에 너무 오래 조리하실 필요는 없어요. 야 채의 숨이 죽을 정도로만 끓여 맛있게 즐겨보세요. 깊은 육수의 맛을 보면 마음까지 금방 따뜻해지실 거예요.','[소중한식사] 소고기 버섯 전골.jpg','소고기 버섯 전골.jpg',null,9,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (39,'[미트클레버] 소갈비찜','미트클레버',35000,10,'F0000','식탁을 빛내는 간편한 메인 요리','많은 인원의 손님을 맞을 때는 취향을 타지 않으면서도 푸짐한 느낌의 메인 요리가 필요하기 마련이에요. 컬리는 식탁을 빛내 줄 메인 메뉴로 미트클레버의 소갈비찜을 제안할게요. 핏물을 빼고, 기름을 손질하고, 일정 시간 동안 고기를 양념에 재워두는 등 손이 많이 가는 과정을 미리 거쳐 포장한 제품이랍니다. 누구 나 좋아할 만한 달콤 짭짤한 감칠맛을 구현한 것은 물론, 고기에 일일이 칼집을 넣어 양념이 속까지 깊이 배어들도록 만들었지 요. 고기만 든든하게 채워서 보내드리니 채소나 당면 사리를 자유롭게 넣어서 조리해보세요.','[미트클레버] 소갈비찜.jpg','소갈비찜.jpg',null,8,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (41,'[비비고] 잔칫집 모둠잡채','비비고',8980,20,'F0000','여럿이 나눠 먹는 대표 메뉴','갖가지 재료들을 한데 버무린 잡채만큼 풍성한 요리도 없는데 요. 자르고 볶는 과정 없이 손쉽게 조리하고 싶다면 지금 소개하 는 상품에 주목해 주세요. 알록 달록한 여섯 가지 고명이 곁들여 진 잔칫집 모둠 잡채랍니다. 알맞게 볶은 국산 돼지고기와 만가 닥 버섯, 당근, 부추 등 맛과 식감이 다양한 재료들이 넉넉히 어 우러졌어요. 간단한 밥 반찬은 물론, 여럿이 나누어 먹는 메인 요 리로도 추천할게요.','[비비고] 잔칫집 모둠잡채.jpg','잔칫집 모둠잡채.jpg',null,6,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (43,'[도리깨침] 건나물 비빔밥세트','도리깨침',10900,5,'F0000','한식의 대표메뉴, 비빔밥을 위한 나물모음','뜨끈한 밥 한 공기를 탁 붓고 쓱쓱비벼먹는 비빔밥, 맛도 건강도 모두 챙길 수 있는 별미인데요. 도리깨침은 특유의 정갈한 손맛 을 발휘해 특별한 비빔밥 세트를 준비했어요. 바로 향 좋고 식감 좋은 건나물을 사용해서 말이지요. 취나물과 시래기 나물, 건호 박, 건가지를 비롯해 쉽게 만나보기 힘든 건뽕잎까지 알차게 꾸 려 넣었습니다. 담백하고 깔끔한 맛에, 들기름과 들깨가루의 고 소함이 진하게 번져 숟가락을 멈출 수 없어요. 특제 소고기 볶음 고추장을 함께 꾸려 넣었으니 밥만 준비해주세요. 노란 달걀 고 명까지 얹어주면 근사한 한 끼가 펼쳐질 거랍니다.','[도리깨침] 건나물 비빔밥세트.jpg','건나물 비빔밥세트.jpg',null,0,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (44,'[도리깨침] 탕평채','도리깨침',6100,21,'F0000','부드럽고 포근한 식감의 조화','우리나라 오랜 전통의 반찬 탕평채를 간편하게 만나보세요. 도 리깨침은 글한 청포묵에 볶은 소고기와 계란 지단, 김 가루를 풍성하게 더해 탕평채를 완성했어요. 소박한 듯 품격있는 조화 가 느껴지는 맛에 간단한 반찬으로도, 손님맞이 한식 차림에 내 기도 제격이죠. 부드럽게 씹히며 짜지 않으니 가족 누구나 즐길 수 있답니다. 최상의 맛을 위해 재료를 개별 포장해 보내드리니, 묵을 살짝 데친 후 재료들을 버무려 완성해보세요. 식탁에 포근 한 맛이 더해질 거예요.','[도리깨침] 탕평채.jpg','탕평채.jpg',null,0,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (54,'[모어댄초콜릿] 내 인생의 해답! 타로카드 초콜릿','모어댄초콜릿',17500,4,'I0000','달콤한 고민 해결사','작고 사소한 고민일수록, 한마디 조언이 크게 느껴지죠. 모어댄 초콜릿은 달콤한 메시지로 해답을 전해줄 타로카드 초콜릿를 선 보입니다. 신비스러운 박스 안에는 색색의 타로카드가 줄지어 서 있는데요. 마음에 드는 카드를 뽑아 포장을 살짝 벗겨내면, 양 증맞은 초콜릿이 모습을 드러냅니다. 1,000여 개에 달하는 문장 중, 오직 내게 전달된 메시지가 초콜릿 위에 적혀있지요. 벨기에 산 초콜릿으로 만들어 그 맛까지 빠지지 않으니, 확인 후에 입 안 으로 쏙 넣어주세요. 달콤하게 즐기다 보면 고민까지 사르르 녹 일 수 있을 거예요.','[모어댄초콜릿] 내 인생의 해답! 타로카드 초콜릿.jpg','내 인생의 해답! 타로카드 초콜릿.jpg',null,0,null);
Insert into KURLYDEV.TBL_PRODUCT (PCODE,PNAME,COMPANY,PRICE,STOCK,CATEGORY,POSTSCRIPT,DESCRIPTION,ORG_FILENAME,STORED_FILENAME,PREGDATE,DISCOUNT,THISWEEK) values (55,'채소','채소',12233,null,'A0000','정렬 망해랴',null,null,null,null,0,null);
